services:
  backend:
    image: oktaviandwip/goback:1
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=database
    networks:
      - coffeeshop

  database:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=oktav
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=coffee
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - coffeeshop

networks:
  coffeeshop:
    external: true
