services:
  backend:
    image: oktaviandwip/goback:1
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=database
    depends_on:
      database:
        condition: service_healthy
    networks:
      - coffeeshop

  database:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=oktav
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=coffee
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "oktav", "-d", "coffee"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - coffeeshop

networks:
  coffeeshop:
    external: true
